name: "Setup FortiClient VPN"
description: "Installs FortiClient VPN and configures a VPN profile"
inputs:
  VPN_HOST:
    description: "VPN Host"
    required: true
  VPN_PORT:
    description: "VPN Port"
    required: true
  VPN_USER:
    description: "VPN Username"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y expect ca-certificates

    - name: Download and Install FortiClient VPN
      shell: bash
      run: |
        wget https://links.fortinet.com/forticlient/deb/vpnagent -O forticlient.deb
        sudo dpkg -i forticlient.deb || echo "First installation attempt failed"

        sudo apt install -y libayatana-appindicator1 libnss3-tools || {
          sudo apt --fix-broken install -y && sudo dpkg --configure -a && sudo apt install -f -y || {
            echo "Dependency installation failed"
          }
        }

        sudo dpkg -i forticlient.deb || { echo "Final installation failed"; exit 1; }

    - name: Verify Installation
      shell: bash
      run: dpkg -l | grep forticlient || echo "FortiClient installation check failed!"

    - name: Create VPN Profile
      shell: bash
      env:
        VPN_HOST:${{ inputs.VPN_HOST }}
        VPN_PORT=${{ inputs.VPN_PORT }}
        VPN_USER=${{ inputs.VPN_USER }}
      run: |
        cat <<EOF > create_vpn_profile.exp
        #!/usr/bin/expect -f
        spawn /opt/forticlient/fortivpn edit myvpn
        expect -re "Type" { send -- "1\r" }
        expect -re "Remote Gateway:" { send -- "$VPN_HOST\r" }
        expect -re "Port" { send -- "$VPN_PORT\r" }
        expect -re "Authentication" { send -- "3\r" }
        expect -re "Certificate" { send -- "3\r" }
        expect eof
        EOF

        chmod +x create_vpn_profile.exp
        ./create_vpn_profile.exp && rm -f create_vpn_profile.exp
