name: FortiClient VPN Setup and Manage

on:
  workflow_dispatch:
    
jobs:
  forticlient-setup:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup FortiClient VPN
        uses: ./.github/actions/forticlient
        with:
          VPN_HOST: ${{ secrets.VPN_HOST }}
          VPN_PORT: ${{ secrets.VPN_PORT }}
          VPN_USER: ${{ secrets.VPN_USER }}


      - name: Set up tmate session
        uses: mxschmitt/action-tmate@v3
        env:
          VPN_HOST: ${{ secrets.VPN_HOST }}
          VPN_PORT: ${{ secrets.VPN_PORT }}
          VPN_USER: ${{ secrets.VPN_USER }}
        with:
          limit-access-to-actor: true

      - name: VPN Status
        run: |
          /opt/forticlient/fortivpn status
